################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Src/config.c \
../Src/main.c \
../Src/sensors.c \
../Src/stm32f1xx_hal_msp.c \
../Src/stm32f1xx_it.c \
../Src/system_stm32f1xx.c \
../Src/usb_device.c \
../Src/usbd_cdc_if.c \
../Src/usbd_conf.c \
../Src/usbd_desc.c 

OBJS += \
./Src/config.o \
./Src/main.o \
./Src/sensors.o \
./Src/stm32f1xx_hal_msp.o \
./Src/stm32f1xx_it.o \
./Src/system_stm32f1xx.o \
./Src/usb_device.o \
./Src/usbd_cdc_if.o \
./Src/usbd_conf.o \
./Src/usbd_desc.o 

C_DEPS += \
./Src/config.d \
./Src/main.d \
./Src/sensors.d \
./Src/stm32f1xx_hal_msp.d \
./Src/stm32f1xx_it.d \
./Src/system_stm32f1xx.d \
./Src/usb_device.d \
./Src/usbd_cdc_if.d \
./Src/usbd_conf.d \
./Src/usbd_desc.d 


# Each subdirectory must supply rules for building sources it contributes
Src/config.o: ../Src/config.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/compiler" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/decadriver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/platform" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/BME280_driver-master" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/lsm9ds1_STdC/driver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/UWB" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/I2C" -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/config.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/main.o: ../Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/compiler" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/decadriver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/platform" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/BME280_driver-master" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/lsm9ds1_STdC/driver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/UWB" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/I2C" -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/main.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/sensors.o: ../Src/sensors.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/compiler" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/decadriver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/platform" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/BME280_driver-master" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/lsm9ds1_STdC/driver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/UWB" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/I2C" -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/sensors.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/stm32f1xx_hal_msp.o: ../Src/stm32f1xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/compiler" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/decadriver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/platform" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/BME280_driver-master" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/lsm9ds1_STdC/driver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/UWB" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/I2C" -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/stm32f1xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/stm32f1xx_it.o: ../Src/stm32f1xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/compiler" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/decadriver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/platform" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/BME280_driver-master" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/lsm9ds1_STdC/driver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/UWB" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/I2C" -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/stm32f1xx_it.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/system_stm32f1xx.o: ../Src/system_stm32f1xx.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/compiler" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/decadriver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/platform" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/BME280_driver-master" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/lsm9ds1_STdC/driver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/UWB" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/I2C" -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/system_stm32f1xx.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/usb_device.o: ../Src/usb_device.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/compiler" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/decadriver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/platform" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/BME280_driver-master" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/lsm9ds1_STdC/driver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/UWB" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/I2C" -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/usb_device.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/usbd_cdc_if.o: ../Src/usbd_cdc_if.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/compiler" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/decadriver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/platform" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/BME280_driver-master" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/lsm9ds1_STdC/driver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/UWB" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/I2C" -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/usbd_cdc_if.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/usbd_conf.o: ../Src/usbd_conf.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/compiler" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/decadriver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/platform" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/BME280_driver-master" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/lsm9ds1_STdC/driver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/UWB" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/I2C" -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/usbd_conf.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/usbd_desc.o: ../Src/usbd_desc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/compiler" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/decadriver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Src/platform" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/BME280_driver-master" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/lsm9ds1_STdC/driver" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/UWB" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/I2C" -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/mgorywoda/Documents/GitHub/DW-Git/DW_Prime/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/usbd_desc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

